<?php

namespace PPE4\Bundle\Repository;

/**
 * TypeDeSignalementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeDeSignalementRepository extends \Doctrine\ORM\EntityRepository
{
}
